{
    'name': 'Product Catalog',
    'version': '1.0',
    'description': 'External catalog metadata for product.template: data source, make, applications, packaged dimensions.',
    'category': 'Sales/Sales',
    'author': 'drellxor',
    'depends': [
        'product',
        'stock',
        'website',
        'brochures',
        'page_message',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/data_source_data.xml',
        'data/cron_data.xml',
        'data/pricelist_data.xml',
        'views/data_source_views.xml',
        'views/product_make_views.xml',
        'views/product_application_views.xml',
        'views/tvh_codes_views.xml',
        'views/res_config_settings_views.xml',
        'views/product_template_views.xml',
        'views/menu.xml',
        'data/backfill.xml',
    ],
    'installable': True,
    'auto_install': False,
}
